#!/usr/bin/env bash
# Script to install a load balancer.
sudo apt-get update
sudo apt-get -y install haproxy
sudo echo "
listen firstbalance
    bind *:80
    balance roundrobin
    server 4574-web-01 54.160.169.188:80 check
    server 4574-web-02 54.209.165.164:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
