#!/usr/bin/env bash
# Script that displays numbers from 1 to 100.
#+Displays FizzBuzz when the number is a multiple of 3 and 5
#+Displays Fizz when the number is multiple of 3
#+Displays Buzz when the number is a multiple of 5
#+Otherwise, displays the number. In a list format.
for i in {1..100}
do
    a=$((i%5))
    b=$((i%3))
    if [ $a -eq 0 ] && [ $b -eq 0 ]
    then
        echo "FizzBuzz"
    elif [ $a -eq 0 ]
    then
        echo "Buzz"
    elif [ $b -eq 0 ]
    then
        echo "Fizz"
    else
        echo "$i"
    fi
done
