#!/usr/bin/env bash
# script that displays the time for 12 hours and 59 minutes:
#+display hours from 0 to 12
#+display minutes from 1 to 59
i="0"
while [ $i -lt 13 ]
do
    echo "Hour:" $i
    j="1"
    while [ $j -lt 60 ]
    do
        echo "$j"
    j=$((j+1))
    done
    i=$((i+1))
done
