#!/usr/bin/env bash
# script that displays the content of the current directory,
#+in a list format, where only the part of the name after the first dash is displayed
LIST="$(ls)"
for i in $LIST
do
    echo "${i//*-}"
done
